### ISSUE TITLE
Why do we need to commit & merge `docs` files?

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/pathways-to-open-science#39]
The Pathways site doesn't render new content unless I commit and merge docs files.

https://github.com/NASA-Openscapes site does not require this.

**Comment by jules32** [comment]
Hi Stef, it's because we haven't set up GitHub Actions on this repository. The GitHub Action will rebuild the site in the cloud rather than you having to build locally and update. The GA makes it easier to edit from the browser and have it immediately update. Andy and I have been talking about the environmental cost of Cloud as well (that energy comes from somewhere) so maybe we when we add that here we can also add exceptions to not rebuild if only updating README for example.

**Comment by stefaniebutland** [comment]
Very helpful thanks! Closing the issue
